{{- if .Values.pki.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: openbao-selfsigned
  namespace: openbao
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openbao-ca
  namespace: openbao
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  secretName: openbao-ca
  isCA: true
  commonName: OpenBao HeteroNetwork Internal CA
  duration: 43800h
  renewBefore: 8760h
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Never
  issuerRef:
    name: openbao-selfsigned
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: openbao-ca
  namespace: openbao
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  ca:
    secretName: openbao-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openbao-server
  namespace: openbao
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretName: openbao-server-tls
  duration: 8760h
  renewBefore: 720h
  dnsNames:
    - openbao
    - openbao.openbao
    - openbao.openbao.svc
    - openbao.openbao.svc.cluster.local
    - openbao-active.openbao.svc.cluster.local
    - '*.openbao-internal.openbao.svc.cluster.local'
  usages:
    - server auth
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  issuerRef:
    name: openbao-ca
    kind: Issuer
{{- end }}
